"""initial glyphar schema

Revision ID: 99f9aa87f580
Revises: 
Create Date: 2026-05-04 23:25:46.457786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Adicionado para garantir suporte ao SQLModel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99f9aa87f580'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_batches',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='batchstatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_files',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('hash_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pages_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('full_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['ocr_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_files_batch_id'), 'ocr_files', ['batch_id'], unique=False)
    op.create_table('ocr_pages',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('layout_type', sa.Enum('SINGLE', 'DOUBLE', 'MULTI', 'COMPLEX', 'UNKNOWN', name='layouttype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_quality', sa.Enum('EXCELLENT', 'GOOD', 'FAIR', 'POOR', 'UNKNOWN', name='pagequality'), nullable=False),
    sa.Column('page_confidence_mean', sa.Float(), nullable=False),
    sa.Column('processing_time_s', sa.Float(), nullable=False),
    sa.Column('config_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_text_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['ocr_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_pages_file_id'), 'ocr_pages', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_pages_file_id'), table_name='ocr_pages')
    op.drop_table('ocr_pages')
    op.drop_index(op.f('ix_ocr_files_batch_id'), table_name='ocr_files')
    op.drop_table('ocr_files')
    op.drop_table('ocr_batches')
    # ### end Alembic commands ###
