"""Complete SSOT alignment with logical/physical separation

Revision ID: 09f6448d3d15
Revises: 
Create Date: 2026-05-07 18:09:21.871411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Suporte ao SQLModel
from pgvector.sqlalchemy import Vector  # Suporte ao pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '09f6448d3d15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_ledger',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('strategy', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('hitl_triggered', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='nisaba'
    )
    op.create_table('interaction_ledger',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_message', sqlmodel.sql.sqltypes.AutoString(length=8192), nullable=False),
    sa.Column('agent_response', sqlmodel.sql.sqltypes.AutoString(length=8192), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('feedback_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='nisaba'
    )
    op.create_table('semantic_experience',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=8192), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='nisaba'
    )
    op.create_table('session_state',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='nisaba'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_state', schema='nisaba')
    op.drop_table('semantic_experience', schema='nisaba')
    op.drop_table('interaction_ledger', schema='nisaba')
    op.drop_table('decision_ledger', schema='nisaba')
    # ### end Alembic commands ###
