# tools/Glyphar/alembic/alembic.ini

[alembic]
# Como o arquivo ini está DENTRO da pasta alembic, o script_location é o próprio diretório
script_location = %(here)s

# Caminho para os modelos (opcional, já resolvemos no env.py, mas ajuda o Alembic)
prepend_sys_path = ../src

# Deixamos vazio pois o env.py lerá da variável de ambiente DATABASE_URL
sqlalchemy.url = driver://user:pass@localhost/dbname

[post_write_hooks]
# Isso ajuda a formatar o código automaticamente se você tiver o ruff/black instalado
# hooks = ruff
# ruff.type = exec
# ruff.executable = %(here)s/.venv/bin/ruff
# ruff.options = check --fix REVISION_SCRIPT

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
